# Generated by Django 5.0.1 on 2024-04-01 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctor_name", models.CharField(max_length=80)),
                ("specialization_doctor", models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name="Appoiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_appoiment", models.DateField()),
                ("time_appoiment", models.TimeField()),
                ("patient_name", models.CharField(max_length=80)),
                ("patient_phone", models.IntegerField()),
                ("reason_for_visit", models.TextField(max_length=400)),
                (
                    "doctor_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dbDoctors.doctors",
                    ),
                ),
            ],
        ),
    ]
