# Generated by Django 5.0.1 on 2024-04-02 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dbDoctors", "0003_remove_appoiment_doctor_name_appoiment_doctor_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appoiment",
            name="doctor_name",
        ),
        migrations.AddField(
            model_name="appoiment",
            name="doctor_name",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="dbDoctors.doctors",
            ),
        ),
    ]
